#!/bin/bash
echo $@ > $FC_TEST_DIRECTORY/ssh-parms
sync
echo $@ | grep "libvirtd" | grep "echo" > /dev/null
if [ $? = 0 ]; then
    echo "/run/user/1000/libvirt/libvirt-sock"
fi
echo $@ | grep "qemu-kvm" > /dev/null
if [ $? = 0 ]; then
    if [ $FC_TEST_USE_QXL = "1" ]; then
        echo "qxl"
    else
        echo "virtio"
    fi
fi
