#!/bin/bash
# vi:ts=2 sw=2 sts=2

# Copyright (C) 2015 Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the licence, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this program; if not, see <http://www.gnu.org/licenses/>.
#
# Author: Alberto Ruiz <aruiz@redhat.com>

#### This script mocks the systemctl behaviour ####

case $1 in
  start)
    if [ "$FC_FAIL" == "true" ] ; then
      exit 1
    fi
    if [ "$2" != "fleet-commander-vnc-session.service" ] ; then
      exit 1
    fi
    touch "/tmp/fleet-commander-start"
  ;;
  stop)
    if [ "$2" != "fleet-commander-vnc-session.service" ] ; then
      exit 1
    fi
    if [ ! -e "/tmp/fleet-commander-start" ] ; then
      exit 1
    fi
    rm "/tmp/fleet-commander-start"
  ;;
esac
exit 0
