install: fcmdr-logger.py
	mkdir -p /home/fc-user/.local/bin
	mkdir -p /home/fc-user/.config/autostart
	chown fc-user -R /home/fc-user/.local
	chown fc-user -R /home/fc-user/.config
	cp fcmdr-logger.py /home/fc-user/.local/bin
	cp data/fcmdr-logger.desktop /home/fc-user/.config/autostart

