#!/bin/bash

function usage {
    echo "Usage: $0 HOST"
}

if [ -z $1 ]; then
    usage
    exit 1
fi

if [ $UID != 0 ]; then
    echo "WARNING: You need to be root in order to have access to dbus service"
fi

PYTHONPATH=/usr/local/lib/fleet-commander su fleet-commander-admin  -c /usr/bin/python -m fleetcommander.admin --datadir /usr/local/share/fleet-commander-admin --host $1
